language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq octave octave-pkg-dev

install:
    - sudo apt-get update
    # Install Miniconda so we can use it to manage dependencies:
    - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda
    - conda info -a
    # Create a conda environment with the base dependencies:
    - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment
    - conda install setuptools nose matplotlib numpy scipy pip
    - pip install oct2py
    # Install the package:
    - python setup.py install

script:
  - cd seawater/test  && nosetests --verbose --nocapture test_result_comparison.py
