language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
virtualenv:
  system_site_packages: true
before_install:
  - pip install numpy
  - pip install scipy
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
  - pip install --use-mirrors oct2py
  - python setup.py install
script:
  - cd tests
  - nosetests --verbose --nocapture test_result_comparison.py
branches:
  only:
    - master
