language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The fix a crash with multiprocessing.
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - conda create --yes -n seawater python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib nose
  - source activate seawater
  - pip install oct2py
  - python setup.py install
script:
  - cd seawater/test  && nosetests --verbose --nocapture test_result_comparison.py
