language: python

env:
    #- CONDA="python=2.7"
    - CONDA="python=3.4"

before_install:
    - sudo apt-add-repository -y ppa:picaso/octave
    - sudo apt-get update -qq
    - sudo apt-get install -qq octave liboctave-dev
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - travis_retry conda create --yes -n test $CONDA --file requirements.txt
    - source activate test
    - travis_retry conda install --yes pip
    - travis_retry pip install -r requirements-dev.txt

script:
    - python setup.py test
